# Generated by Django 4.0.3 on 2022-04-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('employee_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Age', models.PositiveIntegerField(null=True)),
                ('Gender', models.CharField(choices=[(0, 'Female'), (1, 'Male')], max_length=1, null=True)),
                ('Education', models.CharField(max_length=10, null=True)),
                ('Department', models.CharField(max_length=10, null=True)),
                ('Region', models.CharField(max_length=10, null=True)),
                ('Recruitment_Channel', models.CharField(max_length=10, null=True)),
                ('Previous_year_rating', models.PositiveIntegerField(null=True)),
                ('No_of_Trainings', models.PositiveIntegerField(null=True)),
                ('Training_score', models.PositiveIntegerField(null=True)),
                ('Years_of_service', models.PositiveIntegerField(null=True)),
                ('kpi', models.PositiveIntegerField(null=True)),
                ('awards', models.PositiveIntegerField(null=True)),
                ('predictions', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
